CREATE TABLE [cmsETL].[Omnicare_CMR Data_Comprehensive] (
    [Contract Number]                VARCHAR (50) NULL,
    [Subscriber ID]                  VARCHAR (50) NULL,
    [HICN or RRB Number]             VARCHAR (50) NULL,
    [Beneficiary first name]         VARCHAR (50) NULL,
    [Beneficiary middle initial]     VARCHAR (50) NULL,
    [Beneficiary last name]          VARCHAR (50) NULL,
    [Beneficiary DOB  ccyymmdd ]     VARCHAR (50) NULL,
    [Met CMS targeting criteria?]    VARCHAR (50) NULL,
    [Member cognitively impaired?]   VARCHAR (50) NULL,
    [MTM program enrollment date]    VARCHAR (50) NULL,
    [Date met targeting criteria]    VARCHAR (50) NULL,
    [MTM program opt-out date]       VARCHAR (50) NULL,
    [Participant opt-out Reason]     VARCHAR (50) NULL,
    [Offered annual CMR]             VARCHAR (50) NULL,
    [Initial offer date]             VARCHAR (50) NULL,
    [Received CMR written summary?]  VARCHAR (50) NULL,
    [Number of CMRs received]        VARCHAR (50) NULL,
    [Date of CMR 1]                  VARCHAR (50) NULL,
    [Date of CMR 2]                  VARCHAR (50) NULL,
    [CMR Delivery Method]            VARCHAR (50) NULL,
    [Initial CMR Provider]           VARCHAR (50) NULL,
    [Recipient of CMR]               VARCHAR (50) NULL,
    [Number of TMRs]                 VARCHAR (50) NULL,
    [# Drug therapy recommendations] VARCHAR (50) NULL,
    [# Drug therapy resolutions]     VARCHAR (50) NULL,
    [CMR ID]                         VARCHAR (50) NULL,
    [Consultant Name]                VARCHAR (50) NULL,
    [LICENSE#]                       VARCHAR (50) NULL,
    [ST]                             VARCHAR (50) NULL
);

