CREATE TABLE [staging].[cmrQueue] (
    [cmrQueueID]                        INT           NOT NULL,
    [patientID]                         INT           NOT NULL,
    [policyID]                          INT           NOT NULL,
    [serviceType]                       VARCHAR (100) NULL,
    [centerID]                          INT           NOT NULL,
    [queueTypeID]                       INT           NOT NULL,
    [cmrCompletedDate]                  DATE          NULL,
    [patTakeAwayDate]                   DATE          NULL,
    [postHospitalDischarge]             BIT           NULL,
    [priorAuthCode]                     VARCHAR (100) NULL,
    [patImpaired]                       BIT           NULL,
    [cmrRecipientID]                    INT           NULL,
    [hoursOfOperation]                  VARCHAR (500) NULL,
    [additionalNotes]                   VARCHAR (MAX) NULL,
    [recFirstName]                      VARCHAR (100) NULL,
    [recLastName]                       VARCHAR (100) NULL,
    [takeAwaySentToPat]                 BIT           NULL,
    [takeAwayFirstName]                 VARCHAR (100) NULL,
    [takeAwayLastName]                  VARCHAR (100) NULL,
    [sameAsPatAddress]                  BIT           NULL,
    [PharmacistCode]                    INT           NULL,
    [providerID]                        INT           NULL,
    [patAttest]                         BIT           NULL,
    [email]                             VARCHAR (100) NULL,
    [CMRCogImpairedDeterminationTypeID] SMALLINT      NULL,
    [cmrDeliveryTypeID]                 INT           NULL,
    [scheduleDate]                      DATE          NULL,
    [scheduleTime]                      TIME (0)      NULL,
    [cmrScheduleResult]                 VARCHAR (20)  NULL,
    [timeZone]                          INT           NULL,
    [street]                            VARCHAR (300) NULL,
    [street2]                           VARCHAR (300) NULL,
    [city]                              VARCHAR (200) NULL,
    [state]                             CHAR (2)      NULL,
    [zip]                               VARCHAR (10)  NULL,
    [createdDate]                       DATETIME      NOT NULL,
    [modifiedDate]                      DATETIME      NULL,
    [ptTkwyLanguage]                    VARCHAR (20)  NULL,
    [ptTkwyVersion]                     INT           NULL,
    [providerRoleID]                    INT           NULL
);

