CREATE TABLE [staging].[CMS_Beneficiary_MTMPEnrollment_2018] (
    [PatientID]                       INT          NULL,
    [ContractYear]                    INT          NULL,
    [ClientID]                        INT          NULL,
    [DataSetTypeID]                   INT          NULL,
    [BeneficiaryID]                   INT          NULL,
    [BeneficiaryKey]                  VARCHAR (50) NULL,
    [HICN]                            VARCHAR (15) NULL,
    [First_Name]                      VARCHAR (30) NULL,
    [MI]                              VARCHAR (1)  NULL,
    [Last_Name]                       VARCHAR (30) NULL,
    [DOB]                             DATE         NULL,
    [ActiveFromDT]                    DATETIME     NULL,
    [ActiveThruDT]                    DATETIME     NULL,
    [ranker]                          BIGINT       NULL,
    [MTMPEnrollmentID]                INT          NULL,
    [PolicyID]                        INT          NULL,
    [ContractNumber]                  VARCHAR (5)  NULL,
    [MTMPTargetingDate]               DATE         NULL,
    [MTMPEnrollmentFromDate_Actual]   DATE         NULL,
    [MTMPEnrollmentFromDate_Last]     DATE         NULL,
    [MTMPEnrollmentThruDate]          DATETIME     NULL,
    [MTMPEnrollmentThruDate_Inferred] DATETIME     NULL,
    [OptOutReasonCode]                VARCHAR (2)  NULL,
    [OptOutReasonCode_Inferred]       VARCHAR (2)  NULL,
    [ActiveFromTT]                    DATETIME     NULL,
    [ActiveThruTT]                    DATETIME     NULL
);

