CREATE TABLE [staging].[CMS_CMR_STG] (
    [SourceSystem]                 VARCHAR (8)  NULL,
    [ClaimID]                      INT          NULL,
    [mtmServiceDT]                 DATETIME     NULL,
    [ReasonCode]                   INT          NULL,
    [ActionCode]                   INT          NULL,
    [ResultCode]                   INT          NULL,
    [ClaimStatus]                  VARCHAR (50) NULL,
    [ClaimStatusDT]                DATETIME     NULL,
    [PatientID]                    INT          NULL,
    [PharmacyID]                   INT          NULL,
    [NCPDP_NABP]                   VARCHAR (50) NULL,
    [CMRWithSPT]                   INT          NULL,
    [CMROffer]                     INT          NULL,
    [cmrID]                        INT          NULL,
    [CognitivelyImpairedIndicator] VARCHAR (1)  NULL,
    [MethodOfDeliveryCode]         VARCHAR (2)  NULL,
    [MethodOfDeliveryCode_OLD]     VARCHAR (2)  NULL,
    [ProviderCode]                 VARCHAR (2)  NULL,
    [RecipientCode]                VARCHAR (2)  NULL,
    [AuthorizedRepresentative]     VARCHAR (1)  NULL,
    [Topic01]                      VARCHAR (75) NULL,
    [Topic02]                      VARCHAR (75) NULL,
    [Topic03]                      VARCHAR (75) NULL,
    [Topic04]                      VARCHAR (75) NULL,
    [Topic05]                      VARCHAR (75) NULL,
    [MAPCount]                     INT          NULL,
    [SPTDate]                      DATE         NULL,
    [LTC]                          INT          NULL,
    [ContractYear]                 INT          NULL,
    [ClientID]                     INT          NULL,
    [DatasetType_ID]               INT          NULL
);

