CREATE TABLE [staging].[CVS_ODE_Source] (
    [SourceDataType]                                                      VARCHAR (10)  NULL,
    [ChangeDate]                                                          DATETIME      NULL,
    [TIPOpportunityID]                                                    INT           NULL,
    [CVSOpportunityID]                                                    VARCHAR (100) NULL,
    [CVSReimbursementID]                                                  VARCHAR (100) NULL,
    [TIPDetailID]                                                         INT           NULL,
    [TIPResultID]                                                         INT           NULL,
    [TIPResultStatusID]                                                   INT           NULL,
    [TIPStatusID]                                                         INT           NULL,
    [TIPStatusTypeID]                                                     INT           NULL,
    [ClaimID]                                                             INT           NULL,
    [ClaimStatusID]                                                       INT           NULL,
    [NCPDP]                                                               VARCHAR (50)  NULL,
    [NPI]                                                                 VARCHAR (50)  NULL,
    [OpportunityPharmacyPayment]                                          MONEY         NULL,
    [OpportunityOutcome]                                                  VARCHAR (500) NULL,
    [ServiceStatus]                                                       VARCHAR (500) NULL,
    [DeclineReason]                                                       VARCHAR (100) NULL,
    [ServiceDate]                                                         DATETIME      NULL,
    [CloseDate]                                                           DATETIME      NULL,
    [CloseReason]                                                         VARCHAR (500) NULL,
    [ExternalDispositionCode]                                             VARCHAR (500) NULL,
    [CaseFirstViewDate]                                                   DATETIME      NULL,
    [CaseCreationDate]                                                    DATETIME      NULL,
    [CaseAssignedDate]                                                    DATETIME      NULL,
    [OmissionCareGapRule]                                                 VARCHAR (500) NULL,
    [AlertVerifiedTF]                                                     VARCHAR (500) NULL,
    [AlertType]                                                           VARCHAR (500) NULL,
    [SupportingNotes]                                                     VARCHAR (MAX) NULL,
    [Medication cost is too high]                                         VARCHAR (5)   NULL,
    [Patient taking differently than written directions]                  VARCHAR (5)   NULL,
    [Transportation limitations]                                          VARCHAR (5)   NULL,
    [Concerned about potential side effects]                              VARCHAR (5)   NULL,
    [Experienced side effects]                                            VARCHAR (5)   NULL,
    [Too many medications or doses per day]                               VARCHAR (5)   NULL,
    [Believes to be adherent]                                             VARCHAR (5)   NULL,
    [Decreased cognitive function]                                        VARCHAR (5)   NULL,
    [Feels medication is not helping]                                     VARCHAR (5)   NULL,
    [Feels medication is not needed]                                      VARCHAR (5)   NULL,
    [Forgets to take]                                                     VARCHAR (5)   NULL,
    [Limitations on activities of daily living]                           VARCHAR (5)   NULL,
    [Unsure how to use medication]                                        VARCHAR (5)   NULL,
    [Unable to swallow or administer]                                     VARCHAR (5)   NULL,
    [Refill request delay]                                                VARCHAR (5)   NULL,
    [Patient has no concerns or barriers]                                 VARCHAR (5)   NULL,
    [Addressed symptom and side effect management]                        VARCHAR (5)   NULL,
    [Obtained accurately written prescription]                            VARCHAR (5)   NULL,
    [Contacted provider to obtain alternative formulation]                VARCHAR (5)   NULL,
    [Identified area(s) to simplify medication regimen]                   VARCHAR (5)   NULL,
    [Identified cost reduction strategies]                                VARCHAR (5)   NULL,
    [Identified area(s) to adjust medication regimen]                     VARCHAR (5)   NULL,
    [Provided patient education]                                          VARCHAR (5)   NULL,
    [Provided reminder tools or adherence aids]                           VARCHAR (5)   NULL,
    [Offered prescription delivery]                                       VARCHAR (5)   NULL,
    [Addressed limitation to activities of daily living]                  VARCHAR (5)   NULL,
    [Contacted provider to approve refill request]                        VARCHAR (5)   NULL,
    [Patient received samples]                                            VARCHAR (5)   NULL,
    [Prescriber lowered dose]                                             VARCHAR (5)   NULL,
    [Patient obtained medication from an outside source]                  VARCHAR (5)   NULL,
    [Patient is no longer on medication in targeted drug class]           VARCHAR (5)   NULL,
    [Directions written to take "as needed"]                              VARCHAR (5)   NULL,
    [Patient paid cash]                                                   VARCHAR (5)   NULL,
    [Patient was in hospital (or other transition of care)]               VARCHAR (5)   NULL,
    [Patient resides in a facility (LTC, assisted living, hospice, etc.)] VARCHAR (5)   NULL,
    [Patient is deceased]                                                 VARCHAR (5)   NULL,
    [Intervention already occurred]                                       VARCHAR (5)   NULL,
    [Patient had adverse event/allergy to suggested medication]           VARCHAR (5)   NULL,
    [Patient has tried and failed suggested medication]                   VARCHAR (5)   NULL,
    [Patient is already taking the medication]                            VARCHAR (5)   NULL,
    [Recommended therapy is not appropriate for patient]                  VARCHAR (5)   NULL,
    [ReportType]                                                          VARCHAR (255) NULL
);

