CREATE TABLE [staging].[Patient_2017] (
    [patientKey]              BIGINT        IDENTITY (1, 1) NOT NULL,
    [PatientID]               INT           NOT NULL,
    [PatientID_All]           VARCHAR (50)  NULL,
    [ClientID]                INT           NULL,
    [PolicyID]                INT           NULL,
    [CMSContractNumber]       VARCHAR (50)  NULL,
    [HICN]                    VARCHAR (50)  NULL,
    [LTCFlag]                 BIT           NULL,
    [planeffectivedate]       DATETIME      NULL,
    [plantermdate]            DATETIME      NULL,
    [MTMEligibilityDate]      DATETIME      NULL,
    [MTMTermDate]             DATETIME      NULL,
    [OutcomesEligibilityDate] DATETIME      NULL,
    [OutcomesTermDate]        DATETIME      NULL,
    [CMREligible]             BIT           NULL,
    [First_Name]              VARCHAR (50)  NULL,
    [MI]                      VARCHAR (1)   NULL,
    [Last_Name]               VARCHAR (50)  NULL,
    [Gender]                  VARCHAR (1)   NULL,
    [DOB]                     DATETIME      NULL,
    [Address1]                VARCHAR (50)  NULL,
    [Address2]                VARCHAR (50)  NULL,
    [City]                    VARCHAR (50)  NULL,
    [State]                   VARCHAR (2)   NULL,
    [ZipCode]                 VARCHAR (50)  NULL,
    [Phone]                   VARCHAR (50)  NULL,
    [other_info]              VARCHAR (100) NULL,
    [pbp]                     VARCHAR (50)  NULL,
    [PrimaryLanguage]         VARCHAR (50)  NULL,
    [PCP]                     VARCHAR (50)  NULL,
    [MTMCriteriaFlag]         BIT           NULL,
    [StratScore]              VARCHAR (50)  NULL,
    [CMRFlag]                 BIT           NULL,
    [MemberGenKey]            VARCHAR (13)  NULL,
    [activeAsOf]              DATETIME      NOT NULL,
    [activeThru]              DATETIME      NULL,
    [isCurrent]               BIT           NOT NULL,
    [newPatientid_all]        VARCHAR (50)  NULL,
    [alternateID]             VARCHAR (50)  NULL,
    [displayID]               VARCHAR (50)  NULL,
    [ranker]                  BIGINT        NULL
);

