CREATE TABLE [staging].[TC_Events_New3] (
    [PatientID]          VARCHAR (50) NULL,
    [CMSContractNumber]  VARCHAR (50) NULL,
    [HICN]               VARCHAR (50) NULL,
    [MemberMatchID]      VARCHAR (50) NULL,
    [CMSCaseID]          VARCHAR (50) NULL,
    [VendorID]           VARCHAR (50) NULL,
    [ActionDate]         VARCHAR (50) NULL,
    [OutreachType]       VARCHAR (50) NULL,
    [Channel]            VARCHAR (50) NULL,
    [ChannelSubType]     VARCHAR (50) NULL,
    [ChannelValue]       VARCHAR (50) NULL,
    [Message]            VARCHAR (50) NULL,
    [Receiver]           VARCHAR (50) NULL,
    [ReceiverSubType]    VARCHAR (50) NULL,
    [ReceiverValue]      VARCHAR (50) NULL,
    [Outcome]            VARCHAR (50) NULL,
    [OutcomeDescription] VARCHAR (50) NULL,
    [ContractYear]       VARCHAR (50) NULL,
    [Program]            VARCHAR (50) NULL,
    [ProgramSubType]     VARCHAR (50) NULL,
    [CreateDate]         VARCHAR (50) NULL,
    [TIPDetailID]        VARCHAR (50) NULL,
    [Column 22]          VARCHAR (50) NULL
);

