
CREATE VIEW [dbo].[vw_Client_DailyClaims_RPT]
AS

select c.claimid as [Claim ID]
, c.policyid as [Policy ID]
, c.policyNM as [Policy Name]
, cast(c.mtmserviceDT as date) as [MTM Service Date]
, c.[status] as [Status]
, CASE WHEN c.claimValidationProcessed = 0 and isnull(c.claimValidationPaymentProcessed,0) = 0 and c.validated = 0 then 'Validation in progress'
                   WHEN c.claimValidationProcessed = 1 and isnull(c.claimValidationPaymentProcessed,0) = 0 and c.validated = 0 then 'Validation payment Rejected'
                   WHEN (c.claimValidationProcessed = 0 or c.claimValidationProcessed = 1) and isnull(c.claimValidationPaymentProcessed,0) = 0 and c.validated = 1 then 'Validation payment pending'
                   WHEN c.claimValidationProcessed = 1 and c.claimValidationPaymentProcessed = 1 and c.validated = 1 then 'Validation payment paid'
                   ELSE '' END as [Validation Status]
, c.MemberID as [Member ID]
, c.MemberlastNM as [Patient Last Name]
, c.MemberFirstNM as [Patient First Name]
, c.MemberDOB as [Patient DOB]
, c.MemberGender  as [Patient Gender]
, c.MemberPhone as [Patient Phone]
, c.PharmacyNABP as [NABP]
, c.PharmacyName as [Pharmacy Name]
, c.PharmacyState as [State Delivered]
, c.PharmacistlicenseNumber as [RPH License Number] 
, c.pharmacistLastNM + ' ,' + c.pharmacistFirstNM as [RPH Name]
, c.[reason] as [Reason Number]
, c.[reasonNM] as [Reason Name]
, c.[action] as [Action Number]
, c.[actionNM] as [Action Name]
, c.[result] as [Result Number]
, c.[resultNM] as [Result Name]
, c.[serveritylevel] as [Severity Level]
, c.[serveritylevelNM] as [Level Name]
, c.AIM as [AIM Dollar Value]
, c.charges as [MTM Claim Fee]
, SUBSTRING(REPLACE(REPLACE(REPLACE(c.additionalnotes,CHAR(9),''),CHAR(10),''),CHAR(13),''),1,500) as [Additional Notes]
, CASE WHEN isnull(c.cmrDeliveryTypeID,0) = 1 THEN 'face2face' 
		WHEN isnull(c.cmrDeliveryTypeID,0) = 2 THEN 'telephonic' 
		WHEN isnull(c.cmrDeliveryTypeID,0) = 3 THEN 'telehealth' ELSE NULL END as [Method of Delivery]
, CASE WHEN isnull(c.claimfromcmr,0) = 1 THEN 'Y' ELSE 'N' END as [Claim Associated With A CMR]
, CASE WHEN isnull(c.isTipClaim,0) = 1 THEN 'Y' ELSE 'N' END as [Claim Is A Tip Flag] 
, c.tipdetailid as [Tip Detail Id Number]
, c.tiptitle as [Tip Title]
, c.tipidentificationdate  as [Tip Identification Date] 
, c.newMedRxNumber as [Final Rx]
, c.newMedMetricQuantity as [Final Rx Quantity]
, c.newMedDaysSupply as [Final Rx Day Supply]
, c.newMedGpi as [Final Rx GPI]
, c.newMedName as [Final Rx Product Name]
, c.currentMedRxNumber as [Initial Rx]
, c.currentMedMetricQuantity as [Initial Rx Quantity]
, c.currentMedDaysSupply as [Initial Rx Day Supply]
, c.currentMedGpi as [Initial Rx GPI]
, c.currentMedName as [Initial Rx Product Name]
, SUBSTRING(REPLACE(REPLACE(REPLACE(c.currentPrescriberNPI ,CHAR(9),''),CHAR(10),''),CHAR(13),''),1,11) as [Initial Prescriber NPI]
, c.currentMedPrescriber as [Initial Prescriber Name]
, CASE WHEN c.[Adherence - Too many medications or doses per day] IS NULL THEN 'N' ELSE 'Y' END as [Adherence - Too many medications or doses per day]
, CASE WHEN c.[Adherence - Forgets to take on routine days] IS NULL THEN 'N' ELSE 'Y' END as [Adherence - Forgets to take on routine days]
, CASE WHEN c.[Adherence - Forgets to take on non-routine days] IS NULL THEN 'N' ELSE 'Y' END as [Adherence - Forgets to take on non-routine days]
, CASE WHEN c.[Feels medication is not helping] IS NULL THEN 'N' ELSE 'Y' END as [Feels medication is not helping]
, CASE WHEN c.[Feels medication is not needed] IS NULL THEN 'N' ELSE 'Y' END as [Feels medication is not needed]
, CASE WHEN c.[Experienced side effects] IS NULL THEN 'N' ELSE 'Y' END as [Experienced side effects]
, CASE WHEN c.[Concerned about potential side effects] IS NULL THEN 'N' ELSE 'Y' END as [Concerned about potential side effects]
, CASE WHEN c.[Medication cost is too high] IS NULL THEN 'N' ELSE 'Y' END as [Medication cost is too high]
, CASE WHEN c.[Decreased cognitive function] IS NULL THEN 'N' ELSE 'Y' END as [Decreased cognitive function]
, CASE WHEN c.[Limitations on activities of daily living] IS NULL THEN 'N' ELSE 'Y' END as [Limitations on activities of daily living]
, CASE WHEN c.[Transportation limitations prevent pharmacy access] IS NULL THEN 'N' ELSE 'Y' END as [Transportation limitations prevent pharmacy access]
, CASE WHEN c.[Patient taking differently than written directions] IS NULL THEN 'N' ELSE 'Y' END as [Patient taking differently than written directions]
, CASE WHEN c. [Refill request delay] IS NULL THEN 'N' ELSE 'Y' END as [Refill request delay]
, CASE WHEN c.[No barrier identified] IS NULL THEN 'N' ELSE 'Y' END as [No barrier identified]
, CASE WHEN c.[Pharmacy error in directions/delivery/medication] IS NULL THEN 'N' ELSE 'Y' END as [Pharmacy error in directions/delivery/medication]
, CASE WHEN c.refillpickedup IS NULL THEN 'N' ELSE 'Y'END as [Refill Attestation]
, c.[memberRefusalDesc] as [Patient Refusal Reason]
, c.[prescriberRefusalDesc] as [Presciber Refusal Reason]
, cast(c.paiddate as date) as [Paid Date]
, cast(c.claimsubmitdt as date) as [Date Submitted]
, cast(c.lastupdatedt as date) as [Last Updated Date]
, CASE WHEN c.documentationRole = 'Technician (or Student Pharmacist/Intern)' THEN 'Technician' ELSE c.documentationRole END as [Documented User Role]
, c.documentationLastNM + ', ' + c.documentationFirstNM as [Documentation User]
, c.[memberCMSContractNumber] as [CMS Contract Number]
, c.[memberPBP] as [PBP]
, c.timeToComplete as [Time It Took To Complete MTM Service]
, c.healthTestValue as [Health Test Value]
, c.PCPName as [PCP Name]
, CASE WHEN c.pregTestResult = 1 THEN 'Y' WHEN c.pregTestResult = 0 THEN 'N' ELSE NULL END as [Preg Test Result]
, CASE WHEN isnull(c.isLegacyServiceTypeClaim,0) = 1 THEN 'Y' ELSE 'N' END as [Is Legacy Service Type Claim]
, CASE WHEN isnull(c.isEssentialServiceTypeClaim,0) = 1 THEN 'Y' ELSE 'N' END as [Is Essential Service Type Claim]
, CASE WHEN isnull(c.isStarServiceTypeClaim,0) = 1 THEN 'Y' ELSE 'N' END as [Is Star Service Type Claim]
, c.createDT as [createDT]
, c.statusDT as [statusDT]
from outcomesmtm.dbo.clientManagerReport c
where 1=1




