CREATE TABLE [cms].[rpt_CMR_Log] (
    [CMRLogID]                     INT          IDENTITY (1, 1) NOT NULL,
    [BatchID]                      INT          NOT NULL,
    [BeneficiaryID]                INT          NULL,
    [ContractNumber]               VARCHAR (5)  NULL,
    [MTMPEnrollmentFromDate]       DATE         NULL,
    [MTMPEnrollmentThruDate]       DATE         NULL,
    [ClaimID]                      INT          NULL,
    [MTMServiceDT]                 DATE         NULL,
    [ReasonCode]                   CHAR (3)     NULL,
    [ActionCode]                   CHAR (3)     NULL,
    [ResultCode]                   CHAR (3)     NULL,
    [ClaimStatus]                  VARCHAR (50) NULL,
    [ClaimStatusDT]                DATETIME     NULL,
    [PatientID]                    INT          NULL,
    [PharmacyID]                   INT          NULL,
    [CMRWithSPT]                   BIT          NULL,
    [CMROffer]                     BIT          NULL,
    [CMRID]                        INT          NULL,
    [CognitivelyImpairedIndicator] CHAR (1)     NULL,
    [MethodOfDelivery]             CHAR (2)     NULL,
    [ProviderCode]                 CHAR (2)     NULL,
    [RecipientCode]                CHAR (2)     NULL,
    [Topic01]                      VARCHAR (75) NULL,
    [Topic02]                      VARCHAR (75) NULL,
    [Topic03]                      VARCHAR (75) NULL,
    [Topic04]                      VARCHAR (75) NULL,
    [Topic05]                      VARCHAR (75) NULL,
    [MAPCount]                     TINYINT      NULL,
    [CMRCount]                     SMALLINT     NULL,
    [RankAsc]                      TINYINT      NULL,
    [RankDesc]                     TINYINT      NULL,
    [RankCust]                     TINYINT      NULL,
    [RankRpt]                      TINYINT      NULL,
    [CMRSuccess]                   BIT          NULL,
    [LTCIndicator]                 CHAR (1)     NULL,
    [SPTSentDate]                  DATE         NULL,
    PRIMARY KEY CLUSTERED ([CMRLogID] ASC)
);

