CREATE TABLE [dbo].[claim] (
    [claimID]                   INT             NOT NULL,
    [patientid]                 INT             NULL,
    [reasonTypeID]              INT             NULL,
    [actionTypeID]              INT             NULL,
    [resultTypeID]              INT             NULL,
    [estimated_cost]            MONEY           NULL,
    [AIM]                       MONEY           NULL,
    [initDT]                    SMALLDATETIME   NULL,
    [completeDT]                SMALLDATETIME   NULL,
    [resultDT]                  SMALLDATETIME   NULL,
    [otcTherapyName]            VARCHAR (100)   NULL,
    [problemsImproved]          CHAR (2)        NULL,
    [adverseReactions]          CHAR (2)        NULL,
    [therapyCompliant]          CHAR (2)        NULL,
    [refillPickedUp]            CHAR (2)        NULL,
    [useAsDirected]             CHAR (2)        NULL,
    [patRefusalID]              INT             NULL,
    [patRefusalReason]          VARCHAR (1000)  NULL,
    [presRefusalID]             INT             NULL,
    [presRefusalReason]         VARCHAR (1000)  NULL,
    [immunizationDT]            DATETIME        NULL,
    [mtmServiceDT]              DATETIME        NULL,
    [ecaLevelID]                INT             NULL,
    [productName]               VARCHAR (300)   NULL,
    [timeToComplete]            INT             NULL,
    [reasonWaitID]              INT             NULL,
    [expireDT]                  DATETIME        NULL,
    [newMedName]                VARCHAR (300)   NULL,
    [newMedGpi]                 VARCHAR (100)   NULL,
    [newMedRxNumber]            VARCHAR (100)   NULL,
    [newMedDispensedDT]         DATETIME        NULL,
    [newMedMetricQuantity]      DECIMAL (20, 2) NULL,
    [newMedDaysSupply]          DECIMAL (20, 2) NULL,
    [newMedPrescriber]          VARCHAR (100)   NULL,
    [newMedPrescriberID]        VARCHAR (100)   NULL,
    [currentMedName]            VARCHAR (300)   NULL,
    [currentMedGpi]             VARCHAR (100)   NULL,
    [currentMedRxNumber]        VARCHAR (100)   NULL,
    [currentMedDispensedDT]     DATETIME        NULL,
    [currentMedMetricQuantity]  DECIMAL (20, 2) NULL,
    [currentMedDaysSupply]      DECIMAL (20, 2) NULL,
    [currentMedPrescriber]      VARCHAR (100)   NULL,
    [currentPrescriberID]       VARCHAR (100)   NULL,
    [currentMedfromHistory]     VARCHAR (100)   NULL,
    [cmrPostDischarge]          BIT             NULL,
    [initialConsultDT]          DATETIME        NULL,
    [followUpConsultDT]         DATETIME        NULL,
    [therapySatisfied]          CHAR (2)        NULL,
    [adverseReactionsReported]  CHAR (2)        NULL,
    [featureEncounter]          BIT             NULL,
    [charges]                   MONEY           NULL,
    [isTipClaim]                BIT             NULL,
    [createDT]                  DATETIME        NOT NULL,
    [face2face]                 BIT             NULL,
    [cmrFace2Face]              BIT             NULL,
    [cmrPhoneReasonID]          INT             NULL,
    [cmrCompleted]              BIT             NULL,
    [pharmacistID]              INT             NULL,
    [priorAuthCode]             VARCHAR (100)   NULL,
    [tipResultID]               INT             NULL,
    [medicationID]              INT             NULL,
    [paid]                      BIT             NULL,
    [paiddate]                  DATETIME        NULL,
    [funded]                    BIT             NULL,
    [fundeddate]                DATETIME        NULL,
    [claimfromCMR]              BIT             NULL,
    [APIclaim]                  BIT             NULL,
    [currentPrescriberNPI]      VARCHAR (50)    NULL,
    [tipDetailID]               INT             NULL,
    [HealthTestValue]           VARCHAR (25)    NULL,
    [PCPName]                   VARCHAR (50)    NULL,
    [pregTestResult]            BIT             NULL,
    [policyID]                  INT             NULL,
    [invoiced]                  BIT             NULL,
    [invoiceddate]              DATE            NULL,
    [cmrDeliveryTypeID]         INT             NULL,
    [ninetyDayAttestQ1]         BIT             NULL,
    [ninetyDayAttestQ2]         BIT             NULL,
    [refillRxAttestQ1]          BIT             NULL,
    [refillRxAttestQ2]          BIT             NULL,
    [centerID]                  INT             NULL,
    [statusID]                  INT             NULL,
    [submitDT]                  DATETIME        NULL,
    [documentationRoleID]       INT             NULL,
    [invoiceStatusTypeID]       INT             NULL,
    [changeDate]                DATETIME        NULL,
    [condition]                 INT             NULL,
    [labID]                     INT             NULL,
    [currentMedName2]           VARCHAR (300)   NULL,
    [currentMedGpi2]            VARCHAR (100)   NULL,
    [currentMedRxNumber2]       VARCHAR (100)   NULL,
    [currentMedMetricQuantity2] DECIMAL (20, 2) NULL,
    [currentMedDaysSupply2]     DECIMAL (20, 2) NULL,
    [currentMedPrescriber2]     VARCHAR (100)   NULL,
    [currentPrescriberNPI2]     VARCHAR (50)    NULL
);


GO
CREATE NONCLUSTERED INDEX [NC_claim_claimID_statusID_actiontypeid_policyID]
    ON [dbo].[claim]([claimID] ASC, [statusID] ASC, [actionTypeID] ASC, [policyID] ASC)
    INCLUDE([centerID], [patientid], [reasonTypeID], [resultTypeID]);


GO
CREATE NONCLUSTERED INDEX [NC_claim_claimid_centerid_patientid_mtmservicedt]
    ON [dbo].[claim]([claimID] ASC, [centerID] ASC, [patientid] ASC, [mtmServiceDT] ASC);

