CREATE TABLE [dbo].[DenverHealthGenericPatientList_Test] (
    [Policy ID]                    VARCHAR (50) NULL,
    [Policy Name]                  VARCHAR (50) NULL,
    [Member ID]                    VARCHAR (50) NULL,
    [Carrier]                      VARCHAR (50) NULL,
    [Account]                      VARCHAR (50) NULL,
    [Group]                        VARCHAR (50) NULL,
    [HICN]                         VARCHAR (50) NULL,
    [Plan Term Date]               VARCHAR (50) NULL,
    [term Reason]                  VARCHAR (50) NULL,
    [First Name]                   VARCHAR (50) NULL,
    [MI]                           VARCHAR (50) NULL,
    [Last Name]                    VARCHAR (50) NULL,
    [CMS Contract ]                VARCHAR (50) NULL,
    [PBP]                          VARCHAR (50) NULL,
    [Gender]                       VARCHAR (50) NULL,
    [DOB]                          VARCHAR (50) NULL,
    [Primary Language]             VARCHAR (50) NULL,
    [Address1]                     VARCHAR (50) NULL,
    [Address2]                     VARCHAR (50) NULL,
    [City]                         VARCHAR (50) NULL,
    [State]                        VARCHAR (50) NULL,
    [Zip Code]                     VARCHAR (50) NULL,
    [Phone]                        VARCHAR (50) NULL,
    [Outcomes Effective Date]      VARCHAR (50) NULL,
    [Outcomes Term Date]           VARCHAR (50) NULL,
    [MTMP Enrollment From Date]    VARCHAR (50) NULL,
    [MTMP Enrollment Thru Date]    VARCHAR (50) NULL,
    [CMR Enrollment Date]          VARCHAR (50) NULL,
    [Current TIP Opportunities]    VARCHAR (50) NULL,
    [CMR Eligible]                 VARCHAR (50) NULL,
    [Currently Targeted for a CMR] VARCHAR (50) NULL,
    [Last CMR Date]                VARCHAR (50) NULL,
    [Last CMR Result Name]         VARCHAR (50) NULL,
    [Pharmacy1 NABP]               VARCHAR (50) NULL,
    [Pharmacy1 Name]               VARCHAR (50) NULL,
    [Pharmacy1 Address1]           VARCHAR (50) NULL,
    [Pharmacy1 Address2]           VARCHAR (50) NULL,
    [Pharmacy1 City]               VARCHAR (50) NULL,
    [Pharmacy1 State]              VARCHAR (50) NULL,
    [Pharmacy1 Zip Code]           VARCHAR (50) NULL,
    [Pharmacy1 Phone]              VARCHAR (50) NULL,
    [Pharmacy2 NABP]               VARCHAR (50) NULL,
    [Pharmacy2 Name]               VARCHAR (50) NULL,
    [Pharmacy2 Address1]           VARCHAR (50) NULL,
    [Pharmacy2 Address2]           VARCHAR (50) NULL,
    [Pharmacy2 City]               VARCHAR (50) NULL,
    [Pharmacy2 State]              VARCHAR (50) NULL,
    [Pharmacy2 Zip Code]           VARCHAR (50) NULL,
    [Pharmacy2 Phone]              VARCHAR (50) NULL,
    [Pharmacy3 NABP]               VARCHAR (50) NULL,
    [Pharmacy3 Name]               VARCHAR (50) NULL,
    [Pharmacy3 Address1]           VARCHAR (50) NULL,
    [Pharmacy3 Address2]           VARCHAR (50) NULL,
    [Pharmacy3 City]               VARCHAR (50) NULL,
    [Pharmacy3 State]              VARCHAR (50) NULL,
    [Pharmacy3 Zip Code]           VARCHAR (50) NULL,
    [Pharmacy3 Phone]              VARCHAR (50) NULL,
    [Consultant Pharmacy NABP]     VARCHAR (50) NULL,
    [Consultant Pharmacy Name]     VARCHAR (50) NULL,
    [Consultant Pharmacy Address1] VARCHAR (50) NULL,
    [Consultant Pharmacy Address2] VARCHAR (50) NULL,
    [Consultant Pharmacy City]     VARCHAR (50) NULL,
    [Consultant Pharmacy State]    VARCHAR (50) NULL,
    [Consultant Pharmacy Zip Code] VARCHAR (50) NULL,
    [Consultant Pharmacy Phone]    VARCHAR (50) NULL
);

