CREATE TABLE [dbo].[GenericPatientList] (
    [ID]                           INT           IDENTITY (1, 1) NOT NULL,
    [PatientID]                    VARCHAR (50)  NULL,
    [PatientID_All]                VARCHAR (50)  NULL,
    [PolicyID]                     VARCHAR (50)  NULL,
    [HICN]                         VARCHAR (50)  NULL,
    [PlanTermDate]                 VARCHAR (50)  NULL,
    [Carrier]                      VARCHAR (50)  NULL,
    [Account]                      VARCHAR (50)  NULL,
    [Group]                        VARCHAR (50)  NULL,
    [termReason]                   VARCHAR (50)  NULL,
    [policyName]                   VARCHAR (50)  NULL,
    [Last_Name]                    VARCHAR (50)  NULL,
    [First_Name]                   VARCHAR (50)  NULL,
    [MI]                           VARCHAR (50)  NULL,
    [CMSContractNumber]            VARCHAR (50)  NULL,
    [pbp]                          VARCHAR (50)  NULL,
    [Gender]                       VARCHAR (50)  NULL,
    [DOB]                          VARCHAR (50)  NULL,
    [PrimaryLanguage]              VARCHAR (50)  NULL,
    [Address1]                     VARCHAR (50)  NULL,
    [Address2]                     VARCHAR (50)  NULL,
    [City]                         VARCHAR (50)  NULL,
    [State]                        VARCHAR (50)  NULL,
    [ZipCode]                      VARCHAR (50)  NULL,
    [Phone]                        VARCHAR (50)  NULL,
    [OutcomesEffectiveDate]        VARCHAR (50)  NULL,
    [OutcomesTermDate]             VARCHAR (50)  NULL,
    [MTMPEnrollmentFromDate]       VARCHAR (50)  NULL,
    [MTMPEnrollmentThruDate]       VARCHAR (50)  NULL,
    [cmrEnrollmentDate]            VARCHAR (50)  NULL,
    [Current TIP Opportunities]    VARCHAR (50)  NULL,
    [CMReligible]                  VARCHAR (50)  NULL,
    [Currently Targeted for a CMR] VARCHAR (255) NULL,
    [Last CMR - Date]              VARCHAR (255) NULL,
    [Last CMR - Result Name]       VARCHAR (255) NULL,
    [Pharmacy1NABP]                VARCHAR (50)  NULL,
    [Pharmacy1Name]                VARCHAR (50)  NULL,
    [Pharmacy1Address1]            VARCHAR (50)  NULL,
    [Pharmacy1Address2]            VARCHAR (50)  NULL,
    [Pharmacy1City]                VARCHAR (50)  NULL,
    [Pharmacy1State]               VARCHAR (50)  NULL,
    [Pharmacy1ZipCode]             VARCHAR (50)  NULL,
    [Pharmacy1Phone]               VARCHAR (50)  NULL,
    [Pharmacy2NABP]                VARCHAR (50)  NULL,
    [Pharmacy2Name]                VARCHAR (50)  NULL,
    [Pharmacy2Address1]            VARCHAR (50)  NULL,
    [Pharmacy2Address2]            VARCHAR (50)  NULL,
    [Pharmacy2City]                VARCHAR (50)  NULL,
    [Pharmacy2State]               VARCHAR (50)  NULL,
    [Pharmacy2ZipCode]             VARCHAR (50)  NULL,
    [Pharmacy2Phone]               VARCHAR (50)  NULL,
    [Pharmacy3NABP]                VARCHAR (50)  NULL,
    [Pharmacy3Name]                VARCHAR (50)  NULL,
    [Pharmacy3Address1]            VARCHAR (50)  NULL,
    [Pharmacy3Address2]            VARCHAR (50)  NULL,
    [Pharmacy3City]                VARCHAR (50)  NULL,
    [Pharmacy3State]               VARCHAR (50)  NULL,
    [Pharmacy3ZipCode]             VARCHAR (50)  NULL,
    [Pharmacy3Phone]               VARCHAR (50)  NULL,
    [ConsultantPharmacyNABP]       VARCHAR (50)  NULL,
    [ConsultantPharmacyName]       VARCHAR (50)  NULL,
    [ConsultantPharmacyAddress1]   VARCHAR (50)  NULL,
    [ConsultantPharmacyAddress2]   VARCHAR (50)  NULL,
    [ConsultantPharmacyCity]       VARCHAR (50)  NULL,
    [ConsultantPharmacyState]      VARCHAR (50)  NULL,
    [ConsultantPharmacyZipCode]    VARCHAR (50)  NULL,
    [ConsultantPharmacyPhone]      VARCHAR (50)  NULL,
    [Client ID]                    VARCHAR (50)  NULL,
    [Client Name]                  VARCHAR (50)  NULL,
    [chain code]                   VARCHAR (50)  NULL,
    [Chain Name]                   VARCHAR (50)  NULL
);

