CREATE TABLE [dbo].[GenericPatientList_Stage] (
    [PatientID]                    INT           NULL,
    [PatientID_All]                VARCHAR (50)  NULL,
    [PolicyID]                     INT           NULL,
    [HICN]                         VARCHAR (50)  NULL,
    [PlanTermDate]                 DATETIME      NULL,
    [Carrier]                      VARCHAR (50)  NULL,
    [Account]                      VARCHAR (50)  NULL,
    [Group]                        VARCHAR (50)  NULL,
    [Policy]                       VARCHAR (50)  NULL,
    [termReason]                   VARCHAR (50)  NULL,
    [policyName]                   VARCHAR (100) NULL,
    [Last_Name]                    VARCHAR (50)  NULL,
    [First_Name]                   VARCHAR (50)  NULL,
    [MI]                           VARCHAR (1)   NULL,
    [CMSContractNumber]            VARCHAR (50)  NULL,
    [pbp]                          VARCHAR (50)  NULL,
    [Gender]                       VARCHAR (1)   NULL,
    [DOB]                          DATETIME      NULL,
    [PrimaryLanguage]              VARCHAR (50)  NULL,
    [Address1]                     VARCHAR (50)  NULL,
    [Address2]                     VARCHAR (50)  NULL,
    [City]                         VARCHAR (50)  NULL,
    [State]                        VARCHAR (2)   NULL,
    [ZipCode]                      VARCHAR (50)  NULL,
    [Phone]                        VARCHAR (50)  NULL,
    [OutcomesEffectiveDate]        DATETIME      NULL,
    [OutcomesTermDate]             DATETIME      NULL,
    [MTMPEnrollmentFromDate]       DATE          NULL,
    [MTMPEnrollmentThruDate]       DATE          NULL,
    [cmrEnrollmentDate]            DATE          NULL,
    [Current TIP Opportunities]    INT           NULL,
    [CMReligible]                  BIT           NULL,
    [Currently Targeted for a CMR] VARCHAR (1)   NULL,
    [Last CMR - Date]              DATETIME      NULL,
    [Last CMR - Result Name]       VARCHAR (100) NULL,
    [Pharmacy1NABP]                VARCHAR (50)  NULL,
    [Pharmacy1Name]                VARCHAR (100) NULL,
    [Pharmacy1Address1]            VARCHAR (50)  NULL,
    [Pharmacy1Address2]            VARCHAR (50)  NULL,
    [Pharmacy1City]                VARCHAR (50)  NULL,
    [Pharmacy1State]               VARCHAR (2)   NULL,
    [Pharmacy1ZipCode]             VARCHAR (50)  NULL,
    [Pharmacy1Phone]               VARCHAR (50)  NULL,
    [Pharmacy2NABP]                VARCHAR (50)  NULL,
    [Pharmacy2Name]                VARCHAR (100) NULL,
    [Pharmacy2Address1]            VARCHAR (50)  NULL,
    [Pharmacy2Address2]            VARCHAR (50)  NULL,
    [Pharmacy2City]                VARCHAR (50)  NULL,
    [Pharmacy2State]               VARCHAR (2)   NULL,
    [Pharmacy2ZipCode]             VARCHAR (50)  NULL,
    [Pharmacy2Phone]               VARCHAR (50)  NULL,
    [Pharmacy3NABP]                VARCHAR (50)  NULL,
    [Pharmacy3Name]                VARCHAR (100) NULL,
    [Pharmacy3Address1]            VARCHAR (50)  NULL,
    [Pharmacy3Address2]            VARCHAR (50)  NULL,
    [Pharmacy3City]                VARCHAR (50)  NULL,
    [Pharmacy3State]               VARCHAR (2)   NULL,
    [Pharmacy3ZipCode]             VARCHAR (50)  NULL,
    [Pharmacy3Phone]               VARCHAR (50)  NULL,
    [ConsultantPharmacyNABP]       VARCHAR (50)  NULL,
    [ConsultantPharmacyName]       VARCHAR (100) NULL,
    [ConsultantPharmacyAddress1]   VARCHAR (50)  NULL,
    [ConsultantPharmacyAddress2]   VARCHAR (50)  NULL,
    [ConsultantPharmacyCity]       VARCHAR (50)  NULL,
    [ConsultantPharmacyState]      VARCHAR (2)   NULL,
    [ConsultantPharmacyZipCode]    VARCHAR (50)  NULL,
    [ConsultantPharmacyPhone]      VARCHAR (50)  NULL,
    [OutcomesEligibilityDate]      SMALLDATETIME NULL,
    [chaincode]                    VARCHAR (50)  NULL
);

