CREATE TABLE [dbo].[HUMANA_Current_Tips_TC2183] (
    [tipActivityReportID]                         INT           IDENTITY (1, 1) NOT NULL,
    [reasoncode]                                  VARCHAR (50)  NULL,
    [reasonTypeDesc]                              VARCHAR (50)  NULL,
    [actionCode]                                  VARCHAR (50)  NULL,
    [actionNM]                                    VARCHAR (50)  NULL,
    [First_Name]                                  VARCHAR (50)  NULL,
    [last_name]                                   VARCHAR (50)  NULL,
    [DOB]                                         VARCHAR (50)  NULL,
    [PRIMARY_NCPDP_NABP]                          VARCHAR (MAX) NULL,
    [Primary_PharmacyName]                        VARCHAR (MAX) NULL,
    [pctFillatCenter]                             VARCHAR (50)  NULL,
    [Is Current pharmacy Contracted]              VARCHAR (50)  NULL,
    [Is Current pharmacy Trained]                 VARCHAR (50)  NULL,
    [Is Current pharmacy Contracted and Trained]  VARCHAR (50)  NULL,
    [tipresultstatuscenterID]                     INT           NULL,
    [tipresultstatusid]                           INT           NULL,
    [patientid]                                   INT           NULL,
    [centerid]                                    INT           NULL,
    [tipdetailid]                                 INT           NULL,
    [policyid]                                    INT           NULL,
    [tiptype]                                     VARCHAR (50)  NULL,
    [30dayrule]                                   TINYINT       NULL,
    [TIP Opportunities]                           TINYINT       NULL,
    [TIP Activity]                                TINYINT       NULL,
    [Approved TIPs]                               TINYINT       NULL,
    [Pending Approval TIPs]                       TINYINT       NULL,
    [Review/resubmit TIPs]                        TINYINT       NULL,
    [Rejected TIPs]                               TINYINT       NULL,
    [Unfinished TIPs]                             TINYINT       NULL,
    [No intervention Necessary TIPs]              TINYINT       NULL,
    [Completed TIPs]                              TINYINT       NULL,
    [Successful TIPs]                             TINYINT       NULL,
    [Successful Approved TIPs]                    TINYINT       NULL,
    [Successful Pending Approval TIPs]            TINYINT       NULL,
    [Unsuccessful TIPs]                           TINYINT       NULL,
    [Prescriber Refusal TIPs]                     TINYINT       NULL,
    [Unable to reach prescriber after 3 attempts] TINYINT       NULL,
    [Patient Refusal TIPs]                        TINYINT       NULL,
    [Patient Unable to Reach TIPs]                TINYINT       NULL,
    [primaryPharmacy]                             TINYINT       NULL,
    [activeasof]                                  DATE          NULL,
    [activethru]                                  DATE          NULL,
    [currently active]                            INT           NULL,
    [withdrawn]                                   INT           NULL,
    [chainid]                                     INT           NULL,
    [Successful Paid TIPs]                        INT           NOT NULL,
    [patientid_all]                               VARCHAR (50)  NULL,
    [policyname]                                  VARCHAR (100) NULL,
    [chainnm]                                     VARCHAR (50)  NULL,
    [centername]                                  VARCHAR (100) NULL,
    [ncpdp_nabp]                                  VARCHAR (50)  NULL,
    [parent_organization_id]                      VARCHAR (6)   NULL,
    [parent_organization_name]                    VARCHAR (35)  NULL,
    [relationship_id]                             VARCHAR (7)   NULL,
    [relationship_id_name]                        VARCHAR (35)  NULL,
    [relationship_type]                           VARCHAR (3)   NULL,
    [tiptitle]                                    VARCHAR (100) NULL,
    [expired]                                     BIT           NULL,
    [FILEYEAR2018]                                INT           NULL,
    [FILEYEAR2017]                                INT           NULL
);

