CREATE TABLE [dbo].[NCPDP_Provider] (
    [NCPDP_ProviderID]                                INT          NOT NULL,
    [NCPDP_Provider_ID]                               VARCHAR (7)  NULL,
    [Legal_Business_Name]                             VARCHAR (60) NULL,
    [Name_(Doing_Business_As_Name)]                   VARCHAR (60) NULL,
    [Doctor_Name_(NPDS_Only)]                         VARCHAR (60) NULL,
    [Store_Number]                                    VARCHAR (10) NULL,
    [Physical_Location_Address_1]                     VARCHAR (55) NULL,
    [Physical_Location_Address_2]                     VARCHAR (55) NULL,
    [Physical_Location_City]                          VARCHAR (30) NULL,
    [Physical_Location_State_Code]                    VARCHAR (2)  NULL,
    [Physical_Location_Zip_Code]                      VARCHAR (9)  NULL,
    [Physical_Location_Phone_Number]                  VARCHAR (10) NULL,
    [Physical_Location_Extension]                     VARCHAR (5)  NULL,
    [Physical_Location_FAX_Number]                    VARCHAR (10) NULL,
    [Physical_Location_E-Mail_Address]                VARCHAR (50) NULL,
    [Physical_Location_Cross_Street_or_Directions]    VARCHAR (50) NULL,
    [Physical_Location_County/Parish]                 VARCHAR (5)  NULL,
    [Physical_Location_MSA]                           VARCHAR (4)  NULL,
    [Physical_Location_PMSA]                          VARCHAR (4)  NULL,
    [Physical_Location_24_Hour_Operation_Flag]        VARCHAR (1)  NULL,
    [Physical_Location_Provider_Hours]                VARCHAR (35) NULL,
    [Physical_Location_Congressional_Voting_District] VARCHAR (4)  NULL,
    [Physical_Location_Language_Code_1]               VARCHAR (2)  NULL,
    [Physical_Location_Language_Code_2]               VARCHAR (2)  NULL,
    [Physical_Location_Language_Code_3]               VARCHAR (2)  NULL,
    [Physical_Location_Language_Code_4]               VARCHAR (2)  NULL,
    [Physical_Location_Language_Code_5]               VARCHAR (2)  NULL,
    [Physical_Location_Store_Open_Date]               DATE         NULL,
    [Physical_Location_Store_Closure_Date]            DATE         NULL,
    [Mailing_Address_1]                               VARCHAR (55) NULL,
    [Mailing_Address_2]                               VARCHAR (55) NULL,
    [Mailing_Address_City]                            VARCHAR (30) NULL,
    [Mailing_Address_State_Code]                      VARCHAR (2)  NULL,
    [Mailing_Address_Zip_Code]                        VARCHAR (9)  NULL,
    [Contact_Last_Name]                               VARCHAR (20) NULL,
    [Contact_First_Name]                              VARCHAR (20) NULL,
    [Contact_Middle_Initial]                          VARCHAR (1)  NULL,
    [Contact_Title]                                   VARCHAR (30) NULL,
    [Contact_Phone_Number]                            VARCHAR (10) NULL,
    [Contact_Extension]                               VARCHAR (5)  NULL,
    [Contact_E-Mail_Address]                          VARCHAR (50) NULL,
    [Dispenser_Class_Code]                            VARCHAR (2)  NULL,
    [Provider_Type_Code_(primary)]                    VARCHAR (2)  NULL,
    [Provider_Type_Code_(secondary)]                  VARCHAR (2)  NULL,
    [Provider_Type_Code_(tertiary)]                   VARCHAR (2)  NULL,
    [Medicare_Provider_(supplier)_ID]                 VARCHAR (10) NULL,
    [National_Provider_ID_(NPI)]                      VARCHAR (10) NULL,
    [DEA_Registration_ID]                             VARCHAR (12) NULL,
    [DEA_Expiration_Date]                             DATE         NULL,
    [Federal_Tax_ID_(EIN)]                            VARCHAR (15) NULL,
    [State_Income_Tax_ID_Number]                      VARCHAR (15) NULL,
    [Deactivation_Code]                               VARCHAR (2)  NULL,
    [Reinstatement_Code]                              VARCHAR (2)  NULL,
    [Reinstatement_Date]                              DATE         NULL,
    [Transaction Code (Transaction File Only)]        VARCHAR (1)  NULL,
    [Transaction Date (Transaction File Only)]        DATE         NULL,
    [Active]                                          BIT          NOT NULL,
    [fileid]                                          INT          NOT NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [UC_NCPDP_Provider_NCPDP_ProviderID_dbo]
    ON [dbo].[NCPDP_Provider]([NCPDP_ProviderID] ASC);

