CREATE TABLE [dbo].[NPI_For_TC-2523] (
    [Id]  INT          IDENTITY (1, 1) NOT NULL,
    [NPI] VARCHAR (50) NULL,
    CONSTRAINT [PK_NPI_For_TC-2522] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 80)
);

