CREATE TABLE [dbo].[PHI_issue_for_vw_patientTipDetailReport_final] (
    [sql_handle]             VARBINARY (64) NOT NULL,
    [statement_start_offset] INT            NOT NULL,
    [statement_end_offset]   INT            NOT NULL,
    [plan_generation_num]    BIGINT         NULL,
    [plan_handle]            VARBINARY (64) NOT NULL,
    [creation_time]          DATETIME       NULL,
    [last_execution_time]    DATETIME       NULL,
    [execution_count]        BIGINT         NOT NULL,
    [total_worker_time]      BIGINT         NOT NULL,
    [last_worker_time]       BIGINT         NOT NULL,
    [min_worker_time]        BIGINT         NOT NULL,
    [max_worker_time]        BIGINT         NOT NULL,
    [total_physical_reads]   BIGINT         NOT NULL,
    [last_physical_reads]    BIGINT         NOT NULL,
    [min_physical_reads]     BIGINT         NOT NULL,
    [max_physical_reads]     BIGINT         NOT NULL,
    [total_logical_writes]   BIGINT         NOT NULL,
    [last_logical_writes]    BIGINT         NOT NULL,
    [min_logical_writes]     BIGINT         NOT NULL,
    [max_logical_writes]     BIGINT         NOT NULL,
    [total_logical_reads]    BIGINT         NOT NULL,
    [last_logical_reads]     BIGINT         NOT NULL,
    [min_logical_reads]      BIGINT         NOT NULL,
    [max_logical_reads]      BIGINT         NOT NULL,
    [total_clr_time]         BIGINT         NOT NULL,
    [last_clr_time]          BIGINT         NOT NULL,
    [min_clr_time]           BIGINT         NOT NULL,
    [max_clr_time]           BIGINT         NOT NULL,
    [total_elapsed_time]     BIGINT         NOT NULL,
    [last_elapsed_time]      BIGINT         NOT NULL,
    [min_elapsed_time]       BIGINT         NOT NULL,
    [max_elapsed_time]       BIGINT         NOT NULL,
    [query_hash]             BINARY (8)     NULL,
    [query_plan_hash]        BINARY (8)     NULL,
    [total_rows]             BIGINT         NULL,
    [last_rows]              BIGINT         NULL,
    [min_rows]               BIGINT         NULL,
    [max_rows]               BIGINT         NULL,
    [statement_sql_handle]   VARBINARY (64) NULL,
    [statement_context_id]   BIGINT         NULL,
    [total_dop]              BIGINT         NULL,
    [last_dop]               BIGINT         NULL,
    [min_dop]                BIGINT         NULL,
    [max_dop]                BIGINT         NULL,
    [total_grant_kb]         BIGINT         NULL,
    [last_grant_kb]          BIGINT         NULL,
    [min_grant_kb]           BIGINT         NULL,
    [max_grant_kb]           BIGINT         NULL,
    [total_used_grant_kb]    BIGINT         NULL,
    [last_used_grant_kb]     BIGINT         NULL,
    [min_used_grant_kb]      BIGINT         NULL,
    [max_used_grant_kb]      BIGINT         NULL,
    [total_ideal_grant_kb]   BIGINT         NULL,
    [last_ideal_grant_kb]    BIGINT         NULL,
    [min_ideal_grant_kb]     BIGINT         NULL,
    [max_ideal_grant_kb]     BIGINT         NULL,
    [total_reserved_threads] BIGINT         NULL,
    [last_reserved_threads]  BIGINT         NULL,
    [min_reserved_threads]   BIGINT         NULL,
    [max_reserved_threads]   BIGINT         NULL,
    [total_used_threads]     BIGINT         NULL,
    [last_used_threads]      BIGINT         NULL,
    [min_used_threads]       BIGINT         NULL,
    [max_used_threads]       BIGINT         NULL,
    [Script]                 NVARCHAR (MAX) NULL,
    [id]                     INT            IDENTITY (1, 1) NOT NULL,
    PRIMARY KEY CLUSTERED ([id] ASC)
);

