CREATE TABLE [dbo].[TIPDetailRuleStaging] (
    [TIPDetailRuleID]              INT             NOT NULL,
    [tipdetailid]                  INT             NULL,
    [overview]                     VARCHAR (8000)  NULL,
    [formulary]                    BIT             NULL,
    [lookback]                     INT             NOT NULL,
    [reasonTypeID]                 INT             NULL,
    [actionTypeID]                 INT             NULL,
    [ecaLevelID]                   INT             NULL,
    [isAgeDependent]               BIT             NULL,
    [startAge]                     INT             NULL,
    [endAge]                       INT             NULL,
    [StarTip]                      BIT             NULL,
    [directLoadTip]                BIT             NULL,
    [longitudinalTip]              BIT             NULL,
    [publishTip]                   BIT             NULL,
    [YTDRange]                     BIT             NULL,
    [targetedPDC]                  BIT             NULL,
    [targetedPDCPCT]               DECIMAL (20, 2) NULL,
    [targetedPDCRatioMin]          DECIMAL (20, 2) NULL,
    [targetedPDCRatioMax]          DECIMAL (20, 2) NULL,
    [PDCRange]                     BIT             NULL,
    [PDCRangeMin]                  DECIMAL (20, 2) NULL,
    [PDCRangeMax]                  DECIMAL (20, 2) NULL,
    [generateOnSupply]             BIT             NULL,
    [generateOnSupplyRule]         VARCHAR (50)    NULL,
    [generateOnSupplyRuleValue]    INT             NULL,
    [TIPTypeID]                    SMALLINT        NULL,
    [active]                       BIT             NULL,
    [activeasof]                   DATETIME        NOT NULL,
    [activethru]                   DATETIME        NULL,
    [defaultRegenerationDays]      INT             NULL,
    [NINRegenerationDays]          INT             NULL,
    [DefaultMaxPublishesPerYear]   TINYINT         NULL,
    [NINMaxPublishesPerYear]       TINYINT         NULL,
    [MedSyncTool]                  BIT             NOT NULL,
    [primaryPharmacyOnly]          BIT             NOT NULL,
    [dispensingPharmacyOnly]       BIT             NOT NULL,
    [directTipLoadRunRules]        BIT             NULL,
    [IsMedRecTIP]                  BIT             NULL,
    [MedRecDaysToCompleteService]  TINYINT         NULL,
    [MedRecDaysForFollowupService] TINYINT         NULL,
    [labID]                        INT             NULL
);

