CREATE TABLE [dbo].[TIPDetailRule] (
    [TIPDetailRuleID]                    INT             NOT NULL,
    [tipdetailid]                        INT             NOT NULL,
    [overview]                           VARCHAR (8000)  NULL,
    [formulary]                          BIT             NOT NULL,
    [lookback]                           INT             NOT NULL,
    [reasonTypeID]                       INT             NULL,
    [actionTypeID]                       INT             NULL,
    [ecaLevelID]                         INT             NULL,
    [isAgeDependent]                     BIT             NULL,
    [startAge]                           INT             NULL,
    [endAge]                             INT             NULL,
    [StarTip]                            BIT             CONSTRAINT [DF_TIPDetailRule] DEFAULT ((0)) NOT NULL,
    [directLoadTip]                      BIT             CONSTRAINT [DF_TIPDetailRule_customTip] DEFAULT ((0)) NOT NULL,
    [longitudinalTip]                    BIT             NOT NULL,
    [publishTip]                         BIT             NOT NULL,
    [YTDRange]                           BIT             NULL,
    [targetedPDC]                        BIT             NULL,
    [targetedPDCPCT]                     DECIMAL (20, 2) NULL,
    [targetedPDCRatioMin]                DECIMAL (20, 2) NULL,
    [targetedPDCRatioMax]                DECIMAL (20, 2) NULL,
    [PDCRange]                           BIT             NULL,
    [PDCRangeMin]                        DECIMAL (20, 2) NULL,
    [PDCRangeMax]                        DECIMAL (20, 2) NULL,
    [generateOnSupply]                   BIT             NULL,
    [generateOnSupplyRule]               VARCHAR (50)    NULL,
    [generateOnSupplyRuleValue]          INT             NULL,
    [TIPTypeID]                          SMALLINT        NULL,
    [active]                             BIT             NOT NULL,
    [activeasof]                         DATETIME        NOT NULL,
    [activethru]                         DATETIME        NULL,
    [defaultRegenerationDays]            INT             NULL,
    [NINRegenerationDays]                INT             NULL,
    [DefaultMaxPublishesPerYear]         TINYINT         NULL,
    [NINMaxPublishesPerYear]             TINYINT         NULL,
    [MedSyncTool]                        BIT             DEFAULT ((0)) NOT NULL,
    [primaryPharmacyOnly]                BIT             DEFAULT ((0)) NOT NULL,
    [dispensingPharmacyOnly]             BIT             DEFAULT ((0)) NOT NULL,
    [directTipLoadRunRules]              BIT             DEFAULT ((0)) NULL,
    [IsMedRecTIP]                        BIT             DEFAULT ((0)) NULL,
    [MedRecDaysToCompleteService]        TINYINT         NULL,
    [MedRecDaysForFollowupService]       TINYINT         NULL,
    [labID]                              INT             NULL,
    [medsynclookback]                    SMALLINT        NULL,
    [medsyncdaysforward]                 SMALLINT        NULL,
    [medsyncpercentage]                  TINYINT         NULL,
    [expirationRegenerationDays]         SMALLINT        NULL,
    [maxExpirationRegenerationPublishes] SMALLINT        NULL,
    [expirationOfTIPAnchorDateType]      VARCHAR (10)    DEFAULT ('EOY') NOT NULL,
    [expirationOfTIPDays]                SMALLINT        DEFAULT ((0)) NOT NULL,
    [displayExpirationAnchorDateType]    VARCHAR (10)    NULL,
    [displayExpirationDays]              SMALLINT        NULL,
    [urgencyIndicatorAnchorDateType]     VARCHAR (10)    NULL,
    [urgencyIndicatorDays]               SMALLINT        NULL,
    [medSyncLogic]                       VARCHAR (50)    NULL
);


GO
CREATE CLUSTERED INDEX [PK_TIPDetailRule]
    ON [dbo].[TIPDetailRule]([TIPDetailRuleID] ASC);

