CREATE TABLE [dbo].[TIPType] (
    [TIPTypeID] SMALLINT      NOT NULL,
    [TipType]   VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_TIPType] PRIMARY KEY CLUSTERED ([TipType] ASC) WITH (FILLFACTOR = 80)
);

