CREATE TABLE [dbo].[UHC_RetailerKey_PharmacyTIPs_30] (
    [chainID]                                                                       NVARCHAR (50)  NULL,
    [ChainName]                                                                     NVARCHAR (200) NULL,
    [Pharmacy NABP]                                                                 NVARCHAR (50)  NULL,
    [centerid]                                                                      BIGINT         NOT NULL,
    [Pharmacy Name]                                                                 NVARCHAR (255) NULL,
    [Pharmacy Address]                                                              NVARCHAR (255) NULL,
    [Pharmacy City]                                                                 NVARCHAR (100) NULL,
    [Pharmacy State]                                                                NVARCHAR (100) NULL,
    [Pharmacy Zip]                                                                  NVARCHAR (100) NULL,
    [Needs Refill]                                                                  NVARCHAR (255) NULL,
    [Needs Refill Total Opportunities]                                              DECIMAL (18)   NULL,
    [Needs Refill Count of Opportunities > 7 days]                                  DECIMAL (18)   NULL,
    [Needs Refill Count of Completed TIPs]                                          DECIMAL (18)   NULL,
    [Needs Refill Count of Successful TIPs]                                         DECIMAL (18)   NULL,
    [Needs Refill Count of Active TIPs]                                             DECIMAL (18)   NULL,
    [Needs Refill % Completed]                                                      DECIMAL (5, 2) NULL,
    [Needs Refill % Success]                                                        DECIMAL (5, 2) NULL,
    [Needs Refill % Net Effective]                                                  DECIMAL (5, 2) NULL,
    [Needs 90 Day Fill]                                                             NVARCHAR (255) NULL,
    [Needs 90 Day Fill Total Opportunities]                                         DECIMAL (18)   NULL,
    [Needs 90 Day Fill Count of Opportunities > 30 days]                            DECIMAL (18)   NULL,
    [Needs 90 Day Fill Count of Completed TIPs]                                     DECIMAL (18)   NULL,
    [Needs 90 Day Fill Count of Successful TIPs]                                    DECIMAL (18)   NULL,
    [Needs 90 Day Fill Count of Active TIPs]                                        DECIMAL (18)   NULL,
    [Needs 90 Day Fill % Completed]                                                 DECIMAL (5, 2) NULL,
    [Needs 90 Day Fill % Success]                                                   DECIMAL (5, 2) NULL,
    [Needs 90 Day Fill % Net Effective]                                             DECIMAL (5, 2) NULL,
    [Needs Drug Therapy - Statin - Diabetes]                                        NVARCHAR (255) NULL,
    [Needs Drug Therapy - Statin - Diabetes Total Opportunities]                    DECIMAL (18)   NULL,
    [Needs Drug Therapy - Statin - Diabetes Count of Opportunities > 30 days]       DECIMAL (18)   NULL,
    [Needs Drug Therapy - Statin - Diabetes Count of Completed TIPs]                DECIMAL (18)   NULL,
    [Needs Drug Therapy - Statin - Diabetes Count of Successful TIPs]               DECIMAL (18)   NULL,
    [Needs Drug Therapy - Statin - Diabetes Count of Active TIPs]                   DECIMAL (18)   NULL,
    [Needs Drug Therapy - Statin - Diabetes % Completed]                            DECIMAL (5, 2) NULL,
    [Needs Drug Therapy - Statin - Diabetes % Success]                              DECIMAL (5, 2) NULL,
    [Needs Drug Therapy - Statin - Diabetes % Net Effective]                        DECIMAL (5, 2) NULL,
    [Needs Drug Therapy - Statin - CVD]                                             NVARCHAR (255) NULL,
    [Needs Drug Therapy - Statin - CVD Total Opportunities]                         DECIMAL (18)   NULL,
    [Needs Drug Therapy - Statin - CVD Count of Opportunities > 30 days]            DECIMAL (18)   NULL,
    [Needs Drug Therapy - Statin - CVD Count of Completed TIPs]                     DECIMAL (18)   NULL,
    [Needs Drug Therapy - Statin - CVD Count of Successful TIPs]                    DECIMAL (18)   NULL,
    [Needs Drug Therapy - Statin - CVD Count of Active TIPs]                        DECIMAL (18)   NULL,
    [Needs Drug Therapy - Statin - CVD % Completed]                                 DECIMAL (5, 2) NULL,
    [Needs Drug Therapy - Statin - CVD % Success]                                   DECIMAL (5, 2) NULL,
    [Needs Drug Therapy - Statin - CVD % Net Effective]                             DECIMAL (5, 2) NULL,
    [Suboptimal Drug - Low-Intensity Statin - CVD]                                  NVARCHAR (255) NULL,
    [Suboptimal Drug - Low-Intensity Statin - CVD Total Opportunities]              DECIMAL (18)   NULL,
    [Suboptimal Drug - Low-Intensity Statin - CVD Count of Opportunities > 30 days] DECIMAL (18)   NULL,
    [Suboptimal Drug - Low-Intensity Statin - CVD Count of Completed TIPs]          DECIMAL (18)   NULL,
    [Suboptimal Drug - Low-Intensity Statin - CVD Count of Successful TIPs]         DECIMAL (18)   NULL,
    [Suboptimal Drug - Low-Intensity Statin - CVD Count of Active TIPs]             DECIMAL (18)   NULL,
    [Suboptimal Drug - Low-Intensity Statin - CVD % Completed]                      DECIMAL (5, 2) NULL,
    [Suboptimal Drug - Low-Intensity Statin - CVD % Success]                        DECIMAL (5, 2) NULL,
    [Suboptimal Drug - Low-Intensity Statin - CVD % Net Effective]                  DECIMAL (5, 2) NULL,
    [Needs Medication Synchronization]                                              NVARCHAR (255) NULL,
    [Needs Medication Synchronization Total Opportunities]                          DECIMAL (18)   NULL,
    [Needs Medication Synchronization Count of Opportunities > 30 days]             DECIMAL (18)   NULL,
    [Needs Medication Synchronization Count of Completed TIPs]                      DECIMAL (18)   NULL,
    [Needs Medication Synchronization Count of Successful TIPs]                     DECIMAL (18)   NULL,
    [Needs Medication Synchronization Count of Active TIPs]                         DECIMAL (18)   NULL,
    [Needs Medication Synchronization % Completed]                                  DECIMAL (5, 2) NULL,
    [Needs Medication Synchronization % Success]                                    DECIMAL (5, 2) NULL,
    [Needs Medication Synchronization % Net Effective]                              DECIMAL (5, 2) NULL,
    [Adherence Monitoring]                                                          NVARCHAR (255) NULL,
    [Adherence Monitoring Total Opportunities]                                      DECIMAL (18)   NULL,
    [Adherence Monitoring Count of Opportunities > 30 days]                         DECIMAL (18)   NULL,
    [Adherence Monitoring Count of Completed TIPs]                                  DECIMAL (18)   NULL,
    [Adherence Monitoring Count of Successful TIPs]                                 DECIMAL (18)   NULL,
    [Adherence Monitoring Count of Active TIPs]                                     DECIMAL (18)   NULL,
    [Adherence Monitoring # of Open Checkpoints]                                    INT            NULL,
    [Adherence Monitoring % Completed]                                              DECIMAL (5, 2) NULL,
    [Adherence Monitoring % Success]                                                DECIMAL (5, 2) NULL,
    [Adherence Monitoring % Net Effective]                                          DECIMAL (5, 2) NULL
);

